const quotesData = {
    0: { quote: 'If I cannot do great things, I can do small things in a great way.', author: 'Dr. Martin Luther King, Jr.' },
    1: { quote: 'Act as if what you do makes a difference. It does.', author: 'William James' },
    2: { quote: 'Be the change that you wish to see in the world.', author: 'Mahatma Ghandi' },
    3: { quote: 'Don\'t sit down and wait for the opportunities to come. Get up and make them.', author: 'Madam C.J. Walker' },
    4: { quote: 'Opportunity is missed by most people because it is dressed in overalls and looks like work.', author: 'Thomas Edison' },
    5: { quote: 'The most difficult thing is the decision to act; the rest is merely tenacity. ', author: 'Amelia Earhart' },
    6: { quote: 'The bad news is time flies. The good news is you\'re the pilot.', author: 'Michael Altshuler' },
    7: { quote: 'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination.', author: 'Jimmy Dean' },
    8: { quote: 'It is often the small steps, not the giant leaps, that bring about the most lasting change.', author: 'Queen Elizabeth II' },
    9: { quote: 'If what you have done yesterday still looks big to you, you haven\'t done much today.', author: 'Mikhail Gorbachev' },
    10: { quote: 'In the long run, you make your own luck — good, bad, or indifferent.', author: 'Loretta Lynn' },
    11: { quote: 'If my mind can conceive it, if my heart can believe it, then I can achieve it.', author: 'Muhammad Ali' },
    12: { quote: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
    13: { quote: 'Never limit yourself because of others\' limited imagination; never limit others because of your own limited imagination', author: 'Mae Jemison' },
    14: { quote: 'We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', author: 'Marie Curie' },
    15: { quote: 'The people who are crazy enough to think they can change the world are the ones who do.', author: 'Steve Jobs' },
    16: { quote: 'I scorched the earth with my talent and I let my light shine.', author: 'André Leon Talley' },
    18: { quote: 'Nothing is impossible. The word itself says \'I\'m possible!\'', author: 'Audrey Hepburn' },
    19: { quote: 'Never bend your head. Always hold it high. Look the world straight in the eye.', author: 'Helen Keller' },
    20: { quote: 'Never allow a person to tell you no who doesn\'t have the power to say yes.', author: 'Eleanor Roosevelt' },
    21: { quote: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
    22: { quote: 'When you have a dream, you\'ve got to grab it and never let go.', author: 'Carol Burnett' },
    23: { quote: 'Let us make our future now, and let us make our dreams tomorrow\'s reality.', author: 'Malala Yousafzai' },
    24: { quote: 'All our dreams can come true — if we have the courage to pursue them.', author: 'Walt Disney' },
    25: { quote: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
    26: { quote: 'All dreams are within reach. All you have to do is keep moving towards them.', author: 'Viola Davis' },
    27: { quote: 'Dreams don\'t have to just be dreams. You can make it a reality; if you just keep pushing and keep trying, then eventually you\'ll reach your goal.', author: 'Naomi Osaka' },
    28: { quote: 'Shoot for the moon. Even if you miss, you\'ll land among the stars.', author: 'Norman Vincent Peale' },
    29: { quote: 'There is nothing impossible to they who will try.', author: 'Alexander the Great' },
    30: { quote: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill'},
    31: { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    32: { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    33: { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
    34: { quote: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
    35: { quote: "No matter what people tell you, words and ideas can change the world.", author: "Robin Williams" },
    36: { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    37: { quote: "It is not in the stars to hold our destiny but in ourselves.", author: "William Shakespeare" },
    38: { quote: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
    39: { quote: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
    40: { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    41: { quote: "Don’t cry because it’s over, smile because it happened.", author: "Dr. Seuss" },
    42: { quote: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
    43: { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    44: { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    45: { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    46: { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    47: { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    48: { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    49: { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    50: { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William B. Sprague" },
    51: { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    52: { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    53: { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    54: { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    55: { quote: "Difficulties in life are intended to make us better, not bitter.", author: "Dan Reeves" },
    56: { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    57: { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    58: { quote: "The best way out is always through.", author: "Robert Frost" },
    59: { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
    60: { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" }
}

export default quotesData