const quotesData = {
    0: { quote: '"If I cannot do great things, I can do small things in a great way."', author: "Dr.Martin Luther King, Jr." },
    1: { quote: '"Act as if what you do makes a difference. It does."', author: 'William James' },
    2: { quote: '"Be the change that you wish to see in the world."', author: 'Mahatma Ghandi' },
    3: { quote: '"Don\'t sit down and wait for the opportunities to come. Get up and make them."', author: 'Madam C.J. Walker' },
    4: { quote: '"Opportunity is missed by most people because it is dressed in overalls and looks like work."', author: 'Thomas Edison' },
    5: { quote: '"The most difficult thing is the decision to act; the rest is merely tenacity." ', author: 'Amelia Earhart' },
    6: { quote: '"The bad news is time flies. The good news is you\'re the pilot."', author: 'Michael Altshuler' },
    7: { quote: '"I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination."', author: 'Jimmy Dean' },
    8: { quote: '"It is often the small steps, not the giant leaps, that bring about the most lasting change."', author: 'Queen Elizabeth II' },
    9: { quote: '"If what you have done yesterday still looks big to you, you haven\'t done much today."', author: 'Mikhail Gorbachev' },
    10: { quote: '"In the long run, you make your own luck — good, bad, or indifferent."', author: 'Loretta Lynn' },
    11: { quote: '"If my mind can conceive it, if my heart can believe it, then I can achieve it."', author: 'Muhammad Ali' },
    12: { quote: '"Believe you can and you\'re halfway there."', author: 'Theodore Roosevelt' },
    13: { quote: '"Never limit yourself because of others\' limited imagination; never limit others because of your own limited imagination"', author: 'Mae Jemison' },
    14: { quote: '"We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained."', author: 'Marie Curie' },
    15: { quote: '"The people who are crazy enough to think they can change the world are the ones who do."', author: 'Steve Jobs' },
    16: { quote: '"I scorched the earth with my talent and I let my light shine."', author: 'André Leon Talley' },
    18: { quote: '"Nothing is impossible. The word itself says \'I\'m possible!\'"', author: 'Audrey Hepburn' },
    19: { quote: '"Never bend your head. Always hold it high. Look the world straight in the eye."', author: 'Helen Keller' },
    20: { quote: '"Never allow a person to tell you no who doesn\'t have the power to say yes."', author: 'Eleanor Roosevelt' },
    21: { quote: '"You are never too old to set another goal or to dream a new dream."', author: 'C.S. Lewis' },
    22: { quote: '"When you have a dream, you\'ve got to grab it and never let go."', author: 'Carol Burnett' },
    23: { quote: '"Let us make our future now, and let us make our dreams tomorrow\'s reality."', author: 'Malala Yousafzai' },
    24: { quote: '"All our dreams can come true — if we have the courage to pursue them."', author: 'Walt Disney' },
    25: { quote: '"Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
    26: { quote: '"All dreams are within reach. All you have to do is keep moving towards them."', author: 'Viola Davis' },
    27: { quote: '"Dreams don\'t have to just be dreams. You can make it a reality; if you just keep pushing and keep trying, then eventually you\'ll reach your goal."', author: 'Naomi Osaka' },
    28: { quote: '"Shoot for the moon. Even if you miss, you\'ll land among the stars."', author: 'Norman Vincent Peale' },
    29: { quote: '"There is nothing impossible to they who will try."', author: 'Alexander the Great' },
    30: { quote: '"Success is not final, failure is not fatal: it is the courage to continue that counts."', author: 'Winston Churchill'}
}

export default quotesData